import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'NYAY ADHAAR',
    'app.tagline': 'Trust. Trace. Transform.',
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.cases': 'Cases',
    'nav.disbursements': 'Disbursements',
    'nav.grievances': 'Grievances',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullname': 'Full Name',
    'auth.role': 'Role',
    'auth.user': 'User',
    'auth.admin': 'Administrator',
    'auth.district_officer': 'District Officer',
    'auth.social_welfare': 'Social Welfare Officer',
    'auth.signin': 'Sign In',
    'auth.register': 'Register',
    'auth.already_account': 'Already have an account?',
    'auth.no_account': "Don't have an account?",
    'welcome.title': 'Direct Benefit Transfer System',
    'welcome.subtitle': 'Ensuring Justice and Dignity for All',
    'welcome.desc': 'Smart, tech-enabled DBT implementation for PCR and PoA Acts with real-time tracking, transparency, and accountability.',
    'welcome.features.verification': 'Aadhaar & DigiLocker Verification',
    'welcome.features.tracking': 'Real-time Fund Tracking',
    'welcome.features.grievance': 'Quick Grievance Redressal',
    'welcome.features.transparent': 'Transparent & Accountable',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'Dashboard Overview',
    'dashboard.total_cases': 'Total Cases',
    'dashboard.pending_disbursements': 'Pending Disbursements',
    'dashboard.active_grievances': 'Active Grievances',
    'dashboard.verified_victims': 'Verified Victims',
    'case.register': 'Register Case',
    'case.type': 'Case Type',
    'case.pcr': 'PCR Act',
    'case.poa': 'PoA Act',
    'case.marriage': 'Inter-caste Marriage',
    'case.status': 'Status',
    'case.registered': 'Registered',
    'case.investigation': 'Under Investigation',
    'case.trial': 'In Trial',
    'case.closed': 'Closed',
    'disbursement.track': 'Track Disbursement',
    'disbursement.status': 'Disbursement Status',
    'disbursement.sanctioned': 'Sanctioned',
    'disbursement.processing': 'Processing',
    'disbursement.disbursed': 'Disbursed',
    'disbursement.failed': 'Failed',
    'grievance.submit': 'Submit Grievance',
    'grievance.type': 'Grievance Type',
    'grievance.delay': 'Delay in Processing',
    'grievance.wrong_amount': 'Wrong Amount',
    'grievance.not_received': 'Not Received',
    'grievance.documentation': 'Documentation Issue',
    'grievance.other': 'Other',
    'chat.title': 'AI Assistant',
    'chat.placeholder': 'Ask me anything about DBT, cases, or grievances...',
    'chat.send': 'Send',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
  },
  hi: {
    'app.title': 'न्याय आधार',
    'app.tagline': 'विश्वास। ट्रेस। रूपांतरण।',
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.cases': 'मामले',
    'nav.disbursements': 'वितरण',
    'nav.grievances': 'शिकायतें',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.logout': 'लॉग आउट',
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.fullname': 'पूरा नाम',
    'auth.role': 'भूमिका',
    'auth.user': 'उपयोगकर्ता',
    'auth.admin': 'प्रशासक',
    'auth.district_officer': 'जिला अधिकारी',
    'auth.social_welfare': 'समाज कल्याण अधिकारी',
    'auth.signin': 'साइन इन करें',
    'auth.register': 'रजिस्टर करें',
    'auth.already_account': 'पहले से खाता है?',
    'auth.no_account': 'खाता नहीं है?',
    'welcome.title': 'प्रत्यक्ष लाभ हस्तांतरण प्रणाली',
    'welcome.subtitle': 'सभी के लिए न्याय और गरिमा सुनिश्चित करना',
    'welcome.desc': 'रीयल-टाइम ट्रैकिंग, पारदर्शिता और जवाबदेही के साथ PCR और PoA अधिनियमों के लिए स्मार्ट, तकनीक-सक्षम DBT कार्यान्वयन।',
    'welcome.features.verification': 'आधार और डिजिलॉकर सत्यापन',
    'welcome.features.tracking': 'रीयल-टाइम फंड ट्रैकिंग',
    'welcome.features.grievance': 'त्वरित शिकायत निवारण',
    'welcome.features.transparent': 'पारदर्शी और जवाबदेह',
    'dashboard.welcome': 'स्वागत है',
    'dashboard.overview': 'डैशबोर्ड अवलोकन',
    'dashboard.total_cases': 'कुल मामले',
    'dashboard.pending_disbursements': 'लंबित वितरण',
    'dashboard.active_grievances': 'सक्रिय शिकायतें',
    'dashboard.verified_victims': 'सत्यापित पीड़ित',
    'case.register': 'मामला दर्ज करें',
    'case.type': 'मामले का प्रकार',
    'case.pcr': 'PCR अधिनियम',
    'case.poa': 'PoA अधिनियम',
    'case.marriage': 'अंतरजातीय विवाह',
    'case.status': 'स्थिति',
    'case.registered': 'पंजीकृत',
    'case.investigation': 'जांच में',
    'case.trial': 'सुनवाई में',
    'case.closed': 'बंद',
    'disbursement.track': 'वितरण ट्रैक करें',
    'disbursement.status': 'वितरण स्थिति',
    'disbursement.sanctioned': 'स्वीकृत',
    'disbursement.processing': 'प्रगति में',
    'disbursement.disbursed': 'वितरित',
    'disbursement.failed': 'विफल',
    'grievance.submit': 'शिकायत दर्ज करें',
    'grievance.type': 'शिकायत का प्रकार',
    'grievance.delay': 'प्रसंस्करण में देरी',
    'grievance.wrong_amount': 'गलत राशि',
    'grievance.not_received': 'प्राप्त नहीं हुआ',
    'grievance.documentation': 'दस्तावेज़ीकरण समस्या',
    'grievance.other': 'अन्य',
    'chat.title': 'AI सहायक',
    'chat.placeholder': 'DBT, मामलों या शिकायतों के बारे में मुझसे कुछ भी पूछें...',
    'chat.send': 'भेजें',
    'theme.light': 'लाइट मोड',
    'theme.dark': 'डार्क मोड',
  },
  ta: {
    'app.title': 'நியாய ஆதார்',
    'app.tagline': 'நம்பிக்கை. கண்காணிப்பு. மாற்றம்.',
    'nav.home': 'முகப்பு',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.cases': 'வழக்குகள்',
    'nav.disbursements': 'விநியோகங்கள்',
    'nav.grievances': 'புகார்கள்',
    'nav.profile': 'சுயவிவரம்',
    'nav.logout': 'வெளியேறு',
    'auth.login': 'உள்நுழைவு',
    'auth.signup': 'பதிவு செய்க',
    'auth.email': 'மின்னஞ்சல்',
    'auth.password': 'கடவுச்சொல்',
    'auth.fullname': 'முழு பெயர்',
    'auth.role': 'பங்கு',
    'auth.user': 'பயனர்',
    'auth.admin': 'நிர்வாகி',
    'auth.district_officer': 'மாவட்ட அலுவலர்',
    'auth.social_welfare': 'சமூக நல அலுவலர்',
    'auth.signin': 'உள்நுழைக',
    'auth.register': 'பதிவு செய்க',
    'auth.already_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'auth.no_account': 'கணக்கு இல்லையா?',
    'welcome.title': 'நேரடி நன்மை பரிமாற்ற அமைப்பு',
    'welcome.subtitle': 'அனைவருக்கும் நீதி மற்றும் கண்ணியத்தை உறுதி செய்தல்',
    'welcome.desc': 'நிகழ்நேர கண்காணிப்பு, வெளிப்படைத்தன்மை மற்றும் பொறுப்புணர்வுடன் PCR மற்றும் PoA சட்டங்களுக்கான ஸ்மார்ட், தொழில்நுட்ப-செயல்படுத்தப்பட்ட DBT செயல்படுத்தல்.',
    'welcome.features.verification': 'ஆதார் & டிஜிலாக்கர் சரிபார்ப்பு',
    'welcome.features.tracking': 'நிகழ்நேர நிதி கண்காணிப்பு',
    'welcome.features.grievance': 'விரைவான புகார் தீர்வு',
    'welcome.features.transparent': 'வெளிப்படையான & பொறுப்புணர்வு',
    'dashboard.welcome': 'வரவேற்பு',
    'dashboard.overview': 'டாஷ்போர்டு கண்ணோட்டம்',
    'dashboard.total_cases': 'மொத்த வழக்குகள்',
    'dashboard.pending_disbursements': 'நிலுவையில் உள்ள விநியோகங்கள்',
    'dashboard.active_grievances': 'செயலில் புகார்கள்',
    'dashboard.verified_victims': 'சரிபார்க்கப்பட்ட பாதிக்கப்பட்டவர்கள்',
    'case.register': 'வழக்கு பதிவு செய்க',
    'case.type': 'வழக்கு வகை',
    'case.pcr': 'PCR சட்டம்',
    'case.poa': 'PoA சட்டம்',
    'case.marriage': 'இனங்களுக்கு இடையிலான திருமணம்',
    'case.status': 'நிலை',
    'case.registered': 'பதிவு செய்யப்பட்டது',
    'case.investigation': 'விசாரணையில்',
    'case.trial': 'விசாரணையில்',
    'case.closed': 'மூடப்பட்டது',
    'disbursement.track': 'விநியோகத்தை கண்காணிக்கவும்',
    'disbursement.status': 'விநியோக நிலை',
    'disbursement.sanctioned': 'அனுமதிக்கப்பட்டது',
    'disbursement.processing': 'செயலாக்கம்',
    'disbursement.disbursed': 'விநியோகிக்கப்பட்டது',
    'disbursement.failed': 'தோல்வி',
    'grievance.submit': 'புகார் சமர்ப்பிக்கவும்',
    'grievance.type': 'புகார் வகை',
    'grievance.delay': 'செயலாக்கத்தில் தாமதம்',
    'grievance.wrong_amount': 'தவறான தொகை',
    'grievance.not_received': 'பெறப்படவில்லை',
    'grievance.documentation': 'ஆவண சிக்கல்',
    'grievance.other': 'மற்றவை',
    'chat.title': 'AI உதவியாளர்',
    'chat.placeholder': 'DBT, வழக்குகள் அல்லது புகார்கள் பற்றி என்னிடம் கேளுங்கள்...',
    'chat.send': 'அனுப்பு',
    'theme.light': 'ஒளி பயன்முறை',
    'theme.dark': 'இருள் பயன்முறை',
  },
  te: {
    'app.title': 'న్యాయ ఆధార్',
    'app.tagline': 'విశ్వాసం. ట్రేస్. రూపాంతరం.',
    'nav.home': 'హోమ్',
    'nav.dashboard': 'డాష్‌బోర్డ్',
    'nav.cases': 'కేసులు',
    'nav.disbursements': 'పంపిణీలు',
    'nav.grievances': 'ఫిర్యాదులు',
    'nav.profile': 'ప్రొఫైల్',
    'nav.logout': 'లాగ్ అవుట్',
    'auth.login': 'లాగిన్',
    'auth.signup': 'సైన్ అప్',
    'auth.email': 'ఇమెయిల్',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.fullname': 'పూర్తి పేరు',
    'auth.role': 'పాత్ర',
    'auth.user': 'వినియోగదారు',
    'auth.admin': 'నిర్వాహకుడు',
    'auth.district_officer': 'జిల్లా అధికారి',
    'auth.social_welfare': 'సామాజిక సంక్షేమ అధికారి',
    'auth.signin': 'సైన్ ఇన్',
    'auth.register': 'నమోదు',
    'auth.already_account': 'ఇప్పటికే ఖాతా ఉందా?',
    'auth.no_account': 'ఖాతా లేదా?',
    'welcome.title': 'ప్రత్యక్ష ప్రయోజన బదిలీ వ్యవస్థ',
    'welcome.subtitle': 'అందరికీ న్యాయం మరియు గౌరవాన్ని నిర్ధారించడం',
    'welcome.desc': 'నిజ-సమయ ట్రాకింగ్, పారదర్శకత మరియు జవాబుదారీతనంతో PCR మరియు PoA చట్టాల కోసం స్మార్ట్, టెక్-ఎనేబుల్డ్ DBT అమలు.',
    'welcome.features.verification': 'ఆధార్ & డిజిలాకర్ ధృవీకరణ',
    'welcome.features.tracking': 'నిజ-సమయ నిధుల ట్రాకింగ్',
    'welcome.features.grievance': 'త్వరిత ఫిర్యాదు పరిష్కారం',
    'welcome.features.transparent': 'పారదర్శక & జవాబుదారీ',
    'dashboard.welcome': 'స్వాగతం',
    'dashboard.overview': 'డాష్‌బోర్డ్ అవలోకనం',
    'dashboard.total_cases': 'మొత్తం కేసులు',
    'dashboard.pending_disbursements': 'పెండింగ్ పంపిణీలు',
    'dashboard.active_grievances': 'క్రియాశీల ఫిర్యాదులు',
    'dashboard.verified_victims': 'ధృవీకరించబడిన బాధితులు',
    'case.register': 'కేసు నమోదు చేయండి',
    'case.type': 'కేసు రకం',
    'case.pcr': 'PCR చట్టం',
    'case.poa': 'PoA చట్టం',
    'case.marriage': 'అంతర్-కుల వివాహం',
    'case.status': 'స్థితి',
    'case.registered': 'నమోదు చేయబడింది',
    'case.investigation': 'దర్యాప్తులో',
    'case.trial': 'విచారణలో',
    'case.closed': 'మూసివేయబడింది',
    'disbursement.track': 'పంపిణీని ట్రాక్ చేయండి',
    'disbursement.status': 'పంపిణీ స్థితి',
    'disbursement.sanctioned': 'అనుమతించబడింది',
    'disbursement.processing': 'ప్రాసెస్ చేస్తోంది',
    'disbursement.disbursed': 'పంపిణీ చేయబడింది',
    'disbursement.failed': 'విఫలమైంది',
    'grievance.submit': 'ఫిర్యాదు సమర్పించండి',
    'grievance.type': 'ఫిర్యాదు రకం',
    'grievance.delay': 'ప్రాసెసింగ్‌లో ఆలస్యం',
    'grievance.wrong_amount': 'తప్పు మొత్తం',
    'grievance.not_received': 'అందుకోలేదు',
    'grievance.documentation': 'డాక్యుమెంటేషన్ సమస్య',
    'grievance.other': 'ఇతరం',
    'chat.title': 'AI సహాయకుడు',
    'chat.placeholder': 'DBT, కేసులు లేదా ఫిర్యాదుల గురించి నన్ను అడగండి...',
    'chat.send': 'పంపండి',
    'theme.light': 'లైట్ మోడ్',
    'theme.dark': 'డార్క్ మోడ్',
  },
  bn: {
    'app.title': 'ন্যায় আধার',
    'app.tagline': 'বিশ্বাস। ট্রেস। রূপান্তর।',
    'nav.home': 'হোম',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.cases': 'মামলা',
    'nav.disbursements': 'বিতরণ',
    'nav.grievances': 'অভিযোগ',
    'nav.profile': 'প্রোফাইল',
    'nav.logout': 'লগ আউট',
    'auth.login': 'লগইন',
    'auth.signup': 'সাইন আপ',
    'auth.email': 'ইমেইল',
    'auth.password': 'পাসওয়ার্ড',
    'auth.fullname': 'পুরো নাম',
    'auth.role': 'ভূমিকা',
    'auth.user': 'ব্যবহারকারী',
    'auth.admin': 'প্রশাসক',
    'auth.district_officer': 'জেলা কর্মকর্তা',
    'auth.social_welfare': 'সমাজকল্যাণ কর্মকর্তা',
    'auth.signin': 'সাইন ইন করুন',
    'auth.register': 'নিবন্ধন করুন',
    'auth.already_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'auth.no_account': 'অ্যাকাউন্ট নেই?',
    'welcome.title': 'প্রত্যক্ষ সুবিধা স্থানান্তর সিস্টেম',
    'welcome.subtitle': 'সকলের জন্য ন্যায়বিচার এবং মর্যাদা নিশ্চিত করা',
    'welcome.desc': 'রিয়েল-টাইম ট্র্যাকিং, স্বচ্ছতা এবং জবাবদিহিতা সহ PCR এবং PoA আইনগুলির জন্য স্মার্ট, প্রযুক্তি-সক্ষম DBT বাস্তবায়ন।',
    'welcome.features.verification': 'আধার ও ডিজিলকার যাচাইকরণ',
    'welcome.features.tracking': 'রিয়েল-টাইম তহবিল ট্র্যাকিং',
    'welcome.features.grievance': 'দ্রুত অভিযোগ নিষ্পত্তি',
    'welcome.features.transparent': 'স্বচ্ছ ও জবাবদিহিতা',
    'dashboard.welcome': 'স্বাগতম',
    'dashboard.overview': 'ড্যাশবোর্ড সংক্ষিপ্ত বিবরণ',
    'dashboard.total_cases': 'মোট মামলা',
    'dashboard.pending_disbursements': 'মুলতুবি বিতরণ',
    'dashboard.active_grievances': 'সক্রিয় অভিযোগ',
    'dashboard.verified_victims': 'যাচাইকৃত ক্ষতিগ্রস্ত',
    'case.register': 'মামলা নিবন্ধন করুন',
    'case.type': 'মামলার ধরন',
    'case.pcr': 'PCR আইন',
    'case.poa': 'PoA আইন',
    'case.marriage': 'আন্তঃ-জাতি বিবাহ',
    'case.status': 'অবস্থা',
    'case.registered': 'নিবন্ধিত',
    'case.investigation': 'তদন্তাধীন',
    'case.trial': 'বিচারে',
    'case.closed': 'বন্ধ',
    'disbursement.track': 'বিতরণ ট্র্যাক করুন',
    'disbursement.status': 'বিতরণ অবস্থা',
    'disbursement.sanctioned': 'অনুমোদিত',
    'disbursement.processing': 'প্রক্রিয়াকরণ',
    'disbursement.disbursed': 'বিতরণ করা হয়েছে',
    'disbursement.failed': 'ব্যর্থ',
    'grievance.submit': 'অভিযোগ জমা দিন',
    'grievance.type': 'অভিযোগের ধরন',
    'grievance.delay': 'প্রক্রিয়াকরণে বিলম্ব',
    'grievance.wrong_amount': 'ভুল পরিমাণ',
    'grievance.not_received': 'প্রাপ্ত হয়নি',
    'grievance.documentation': 'ডকুমেন্টেশন সমস্যা',
    'grievance.other': 'অন্যান্য',
    'chat.title': 'AI সহায়ক',
    'chat.placeholder': 'DBT, মামলা বা অভিযোগ সম্পর্কে আমাকে কিছু জিজ্ঞাসা করুন...',
    'chat.send': 'পাঠান',
    'theme.light': 'লাইট মোড',
    'theme.dark': 'ডার্ক মোড',
  },
  mr: {
    'app.title': 'न्याय आधार',
    'app.tagline': 'विश्वास. ट्रेस. ट्रान्सफॉर्म.',
    'nav.home': 'होम',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.cases': 'प्रकरणे',
    'nav.disbursements': 'वितरण',
    'nav.grievances': 'तक्रारी',
    'nav.profile': 'प्रोफाइल',
    'nav.logout': 'लॉग आउट',
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.fullname': 'पूर्ण नाव',
    'auth.role': 'भूमिका',
    'auth.user': 'वापरकर्ता',
    'auth.admin': 'प्रशासक',
    'auth.district_officer': 'जिल्हा अधिकारी',
    'auth.social_welfare': 'समाज कल्याण अधिकारी',
    'auth.signin': 'साइन इन करा',
    'auth.register': 'नोंदणी करा',
    'auth.already_account': 'आधीपासून खाते आहे?',
    'auth.no_account': 'खाते नाही?',
    'welcome.title': 'प्रत्यक्ष लाभ हस्तांतरण प्रणाली',
    'welcome.subtitle': 'सर्वांसाठी न्याय आणि प्रतिष्ठा सुनिश्चित करणे',
    'welcome.desc': 'रिअल-टाइम ट्रॅकिंग, पारदर्शकता आणि जबाबदारीसह PCR आणि PoA कायद्यांसाठी स्मार्ट, टेक-सक्षम DBT अंमलबजावणी.',
    'welcome.features.verification': 'आधार आणि डिजिलॉकर सत्यापन',
    'welcome.features.tracking': 'रिअल-टाइम फंड ट्रॅकिंग',
    'welcome.features.grievance': 'जलद तक्रार निवारण',
    'welcome.features.transparent': 'पारदर्शक आणि जबाबदार',
    'dashboard.welcome': 'स्वागत आहे',
    'dashboard.overview': 'डॅशबोर्ड विहंगावलोकन',
    'dashboard.total_cases': 'एकूण प्रकरणे',
    'dashboard.pending_disbursements': 'प्रलंबित वितरण',
    'dashboard.active_grievances': 'सक्रिय तक्रारी',
    'dashboard.verified_victims': 'सत्यापित पीडित',
    'case.register': 'प्रकरण नोंदवा',
    'case.type': 'प्रकरणाचा प्रकार',
    'case.pcr': 'PCR कायदा',
    'case.poa': 'PoA कायदा',
    'case.marriage': 'आंतरजातीय विवाह',
    'case.status': 'स्थिती',
    'case.registered': 'नोंदणीकृत',
    'case.investigation': 'तपास सुरू',
    'case.trial': 'खटला सुरू',
    'case.closed': 'बंद',
    'disbursement.track': 'वितरण ट्रॅक करा',
    'disbursement.status': 'वितरण स्थिती',
    'disbursement.sanctioned': 'मंजूर',
    'disbursement.processing': 'प्रक्रिया सुरू',
    'disbursement.disbursed': 'वितरीत',
    'disbursement.failed': 'अयशस्वी',
    'grievance.submit': 'तक्रार सबमिट करा',
    'grievance.type': 'तक्रारीचा प्रकार',
    'grievance.delay': 'प्रक्रियेत विलंब',
    'grievance.wrong_amount': 'चुकीची रक्कम',
    'grievance.not_received': 'मिळाली नाही',
    'grievance.documentation': 'दस्तऐवजीकरण समस्या',
    'grievance.other': 'इतर',
    'chat.title': 'AI सहाय्यक',
    'chat.placeholder': 'DBT, प्रकरणे किंवा तक्रारींबद्दल मला काहीही विचारा...',
    'chat.send': 'पाठवा',
    'theme.light': 'लाइट मोड',
    'theme.dark': 'डार्क मोड',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
